### ISSUE TITLE
Upgrade flatpak package to somrhing >= 1.8.2

### ISSUE THREAD

**Issue by jjardon** [JingOS-team/JingOS#122]
**Describe the bug**
flatpak version in the system (1.6.5) is too old to install some flatpaks (others work fine)
Current Debian and Ubuntu has already the up-to-date versions

**To Reproduce**
- $ flatpak install org.chromium.Chromium
error: Failed to install org.chromium.Chromium: app/org.chromium.Chromium/aarch64/stable needs a later flatpak version (1.8.2)

**Expected behavior**
Chromiuin flatpak should be possible to install

**Desktop (please complete the following information):**
 - OS: JingOS 1.2.0

**Comment by jjardon** [comment]
ok, I tried to workaround the issue installing the flatpak from the ubuntu PPA: https://launchpad.net/~flatpak/+archive/ubuntu/stable

But I got another problem when trying to add it:
```
sudo add-apt-repository ppa:flatpak/stable      
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 108, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 118, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 613, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Jingos/focal
```

I think above is because https://github.com/JingOS-team/JingOS/issues/84

After temporarily changing the `ID` in `/etc/os-release` from `jingos` to `ubuntu` everything worked as expected:
```
$ flatpak --version 
Flatpak 1.12.4
$ flatpak install org.chromium.Chromium
...
$ flatpak run org.chromium.Chromium
...
```

Now I'm enjoying running chromium from a flatpak (which has also the advantage of being a more recent version (97.0.4692.99) than the one that comes with the device (93.0.4577.63)):
![Screenshot_20220123_225854](https://user-images.githubusercontent.com/165288/150702104-143bdf80-11fb-4508-b10b-d363f30dac60.jpg)

**Comment by songlijuan666** [comment]
问题已经反馈开发，我们内部分析一下
